### ISSUE TITLE
Enable CSS Modules options

### ISSUE THREAD

**Issue by mverissimo** [onigoetz/postcss-lightningcss#74]
This is a really good plugin, I'm trying to pass CSS Modules options like: https://lightningcss.dev/css-modules.html#custom-naming-patterns but I think is not possible yet.

**Comment by onigoetz** [comment]
Hi @mverissimo you are correct it seems that this isn't possible yet.

I will see what I can do about it to expose the option directly

**Comment by onigoetz** [comment]
Hi, this should now work fine in version 0.8.1 of the package
