### ISSUE TITLE
CSS Modules JSON

### ISSUE THREAD

**Issue by mverissimo** [onigoetz/postcss-lightningcss#75]
It's me again, maybe is possible a way(callback) to get the JSON output when CSS modules are enabled? Something similar to:
https://github.com/madyankin/postcss-modules#saving-exported-classes

This is really helpful to integrate with other bundlers, like esbuild

**Comment by onigoetz** [comment]
Hmmm, yes sure, will check how this can be done

**Comment by mverissimo** [comment]
Really thanks, this is an amazing feature! I will build a esbuild plugin now 🎉
