### ISSUE TITLE
Read external Browserslist config if `browsers` is not set 

### ISSUE THREAD

**Issue by kytta** [onigoetz/postcss-lightningcss#82]
If the `browsers` property is not set, we should check if there is an external Browserslist config in the repo (`package.json#browserslist`, ` .browserslistrc`, [etc.](https://github.com/browserslist/browserslist#queries)). You can call `browserslist()` with no arguments to get the value from a config: https://github.com/browserslist/browserslist#js-api

P.S. I can help to implement it

**Comment by onigoetz** [comment]
Hi @kytta that would be nice indeed.

I'd be happy to review and merge a PR if you're willing to do it :)
